# Generated by Django 5.2.11 on 2026-02-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerole',
            name='role',
            field=models.CharField(choices=[('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Project Manager', 'Project Manager'), ('Team Lead', 'Team Lead'), ('digital marketing', 'digital marketing'), ('graphic designer', 'graphic designer'), ('UI/UX Designer', 'UI/UX Designer'), ('Content Writer', 'Content Writer'), ('Video Editor', 'Video Editor'), ('Social Media Manager', 'Social Media Manager')], max_length=100),
        ),
    ]
